# Generated by Django 4.1.2 on 2022-11-23 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('description_short', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
