# Generated by Django 4.1.2 on 2022-11-27 13:22

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=payment.models.get_upload_path, verbose_name='Изображение'),
        ),
    ]
