# Generated by Django 4.1.2 on 2022-11-27 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_description_short_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(default='No_name', max_length=50, verbose_name='Имя')),
                ('customer_lastname', models.CharField(default='No_lastname', max_length=50, verbose_name='Фамилия')),
                ('customer_address', models.CharField(db_index=True, default='No_address', max_length=100, verbose_name='Адрес')),
                ('registrated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время регистрации заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество товара')),
                ('price_in_order', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость в заказе')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_elements', to='payment.item', verbose_name='Продукт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='payment.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
    ]
